### ISSUE TITLE
Error training:  'list' has no attribute 'shape'

### ISSUE THREAD

**Issue by dvaldivia** [Wapiti08/DeepLog#13]
While trying to execute `Execution_Path_Anomaly.py` I'm getting error

```
2022-07-26 14:49:19.044873: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-26 14:49:19.044976: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Traceback (most recent call last):
  File "/Users/dvaldivia/dev/Wapiti08/DeepLog/Deeplog_demo/Execution_Path_Anomaly/Execution_Path_Anomaly.py", line 425, in <module>
    model = lstm_model(x_train, y_train)
  File "/Users/dvaldivia/dev/Wapiti08/DeepLog/Deeplog_demo/Execution_Path_Anomaly/Execution_Path_Anomaly.py", line 155, in lstm_model
    model.add(Dense(y.shape[1],activation='softmax'))
AttributeError: 'list' object has no attribute 'shape'
```

The change was introduced in https://github.com/Wapiti08/DeepLog/commit/d590e2b01c54ca1e8e03b88eb8cea6e27d6af398 

since I see that `y_train` is merely a list built by `get_train()` then I'd like to know if this list is expected to have any special class or if perhaps the `num_classes` should be passed manually by calculating the number of different values in `y_train`

for my arguments I'm using the sample files found in the repo, is this correct?
```bash
python Execution_Path_Anomaly.py \
--p1 ../../Deeplog_demo/Dataset/Linux/Clear_Separate_Structured_Logs/Integrated_structured_log.csv \
--p2 ../../Deeplog_demo/Dataset/Linux/Clear_Separate_Structured_Logs/log_value_vector.csv \
--p3 ../../Deeplog_demo/Dataset/Linux/Malicious_Separate_Structured_Logs/Integrated_structured_log.csv \
--p4 ../../Deeplog_demo/Dataset/Linux/Malicious_Separate_Structured_Logs/log_value_vector.csv
```

**Comment by Wapiti08** [comment]
Hi,

Thanks for your question. It is very easy to fix that problem. Just use:
```
 np.array(y)
```
Please do not use the scripts under the demo. It is out of date. Try to execute the related models under the root folder like **Execution_Path/Execution_Path_Anomaly.py**
